// using System.Diagnostics;
// Stopwatch sw = new Stopwatch();
// sw.Start();
int [] arr = 5.Create()
            .FillRandom(0,5);
//arr.ConvertToStringAndPrint();
// sw.Stop();
// Console.WriteLine($"Старт {sw.ElapsedMilliseconds}");
// sw.Reset();
// sw.Start();
// int m = 100000;
// int max = arr.BadGetSum(m);
// sw.Stop();
// Console.WriteLine($"BadGetSum {max} {sw.ElapsedMilliseconds}");
// sw.Reset();
// sw.Start();
// max = arr.GoodGetSum(m);
// sw.Stop();
// Console.WriteLine($"GoodGetSum {max} {sw.ElapsedMilliseconds}");
int [] arr2 = new int[arr.Length];
// int [] arr3 = new int[arr.Length];
// int [] arr4 = new int[arr.Length];
Array.Copy(arr,arr2,arr.Length);
// Array.Copy(arr,arr3,arr.Length);
// Array.Copy(arr,arr4,arr.Length);
arr2.CountingSortDebag();
// arr.ConvertToStringAndPrint();
// arr3.BoobleSort().ConvertToStringAndPrint();
// arr.ConvertToStringAndPrint();
// arr4.CountingSort().ConvertToStringAndPrint();